const store=require('../data/qcasaMarketplaceStore');const base=require('./qcasaController');const clean=v=>String(v||'').trim();
function normalizeVideoUrl(raw){const value=clean(raw);if(!value)return '';const yt=value.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([A-Za-z0-9_-]{6,})/i);return yt?`https://www.youtube.com/embed/${yt[1]}`:value}
function applyVideoAfter(handler,mode){return(req,res,next)=>{const before=req.params?.id?store.findById(req.params.id):null,was=before?.status==='Publicada',ids=new Set(store.properties.map(p=>p.id));handler(req,res,next);const videoUrl=normalizeVideoUrl(req.body?.videoUrl);let p=before;if(mode==='create')p=store.properties.find(x=>!ids.has(x.id));if(!p)return;if((mode==='user-update'||mode==='user-published')&&was&&p.pendingChanges)p.pendingChanges.videoUrl=videoUrl;else p.videoUrl=videoUrl}}
exports.userCreate=applyVideoAfter(base.userCreateProperty,'create');exports.userUpdate=applyVideoAfter(base.userUpdateProperty,'user-update');exports.userPublishedChanges=applyVideoAfter(base.userSubmitPublishedChanges,'user-published');exports.adminCreate=applyVideoAfter(base.adminCreate,'create');exports.adminUpdate=applyVideoAfter(base.adminUpdate,'admin-update');
exports.adminDashboard=(req,res,next)=>{const render=res.render.bind(res);res.render=(view,locals={},cb)=>{if(view==='qcasa/admin/dashboard.njk'){locals.stats=locals.stats||{};locals.stats.total=store.properties.length;locals.stats.rejected=store.properties.filter(p=>p.status==='Rechazada').length;locals.stats.drafts=store.properties.filter(p=>p.status==='Borrador').length;const pub=store.properties.filter(p=>p.status==='Publicada');locals.opportunities={noVideo:pub.filter(p=>!p.videoUrl).length,lowPhotos:pub.filter(p=>!Array.isArray(p.images)||p.images.length<5).length,noInquiries:pub.filter(p=>!store.inquiries.some(i=>i.propertyId===p.id)).length,highInterest:pub.slice().sort((a,b)=>(b.views||0)-(a.views||0)).slice(0,3)}}return render(view,locals,cb)};return base.adminDashboard(req,res,next)};
function qualityFor(p){const checks=[['Fotos',Array.isArray(p.images)&&p.images.length>=5],['Ubicación',Boolean(p.city&&p.department&&p.lat&&p.lng)],['Descripción',String(p.summary||'').trim().length>=80],['Video',Boolean(p.videoUrl)],['Características',Boolean(p.area&&(p.bedrooms||p.bathrooms||p.category))],['Contacto',Boolean(p.ownerPhone||p.contact)]];const ok=checks.filter(x=>x[1]).length;return{score:Math.round(ok/checks.length*100),missing:checks.filter(x=>!x[1]).map(x=>x[0]).join(' · ')}}
exports.detail=(req,res,next)=>{const render=res.render.bind(res);res.render=(view,locals={},cb)=>{if(view==='qcasa/detail.njk'&&locals.property){const p=locals.property;locals.galleryImages=JSON.stringify((p.images&&p.images.length?p.images:[p.image])).replace(/</g,'\\u003c');locals.similar=store.properties.filter(x=>x.status==='Publicada'&&x.id!==p.id).slice(0,3)}return render(view,locals,cb)};return base.detail(req,res,next)};
exports.adminProperties=(req,res)=>{const selected=clean(req.query.status)||'Todos',all=store.properties.slice().sort((a,b)=>new Date(b.updatedAt||b.createdAt||0)-new Date(a.updatedAt||a.createdAt||0));const counts={Todos:all.length,Publicada:all.filter(p=>p.status==='Publicada').length,Pendiente:all.filter(p=>p.status==='Pendiente').length,Rechazada:all.filter(p=>p.status==='Rechazada').length,Borrador:all.filter(p=>p.status==='Borrador').length,Cambios:all.filter(p=>p.changeStatus==='Pendiente'&&p.pendingChanges).length,Videos:all.filter(p=>p.videoUrl||p.pendingChanges?.videoUrl).length};let properties=all;if(selected==='Cambios')properties=all.filter(p=>p.changeStatus==='Pendiente'&&p.pendingChanges);else if(selected==='Videos')properties=all.filter(p=>p.videoUrl||p.pendingChanges?.videoUrl);else if(selected!=='Todos')properties=all.filter(p=>p.status===selected);res.render('qcasa/admin/properties.njk',{title:'Propiedades | Administración QCASA',properties:properties.map(p=>({...p,quality:qualityFor(p)})),selected,counts})};
exports.adminSetStatus=(req,res)=>{const p=store.findById(req.params.id);if(!p)return res.status(404).send('Propiedad no encontrada.');const status=clean(req.body.status);if(!['Borrador','Pendiente','Publicada','Rechazada'].includes(status))return res.status(400).send('Estado inválido.');const old=p.status;p.status=status;p.updatedAt=new Date().toISOString();if(status==='Publicada'){p.reviewedAt=new Date().toISOString();p.reviewNote='Publicada por administración.'}if(p.ownerUserId&&old!==status)store.addNotification(p.ownerUserId,{type:status==='Publicada'?'success':'info',title:`Estado actualizado: ${status}`,message:`"${p.title}" ahora está ${status.toLowerCase()}.`,propertyId:p.id});res.redirect(req.get('referer')||'/qcasa/admin/propiedades')};
exports.contact=(req,res)=>{const reason=clean(req.body.reason)||'Consulta general',name=clean(req.body.name),phone=clean(req.body.phone),email=clean(req.body.email),message=clean(req.body.message);if(!name||!phone||!message)return res.status(400).send('Completá nombre, teléfono y mensaje.');store.inquiries.unshift({id:`CON-${Date.now()}`,propertyId:null,propertyTitle:`Contacto QCASA · ${reason}`,name,phone,email,message,status:'Nueva',source:'Contacto general',reason,createdAt:new Date().toISOString()});res.redirect('/qcasa?contacto=1')};
const demo=store.findById('QC-1001');if(demo&&!demo.videoUrl){demo.videoUrl='https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4';demo.videoLabel='Video demo'}
