const store=require('../data/qcasaMarketplaceStore');const base=require('./qcasaController');const clean=v=>String(v||'').trim(),email=v=>clean(v).toLowerCase(),phone=v=>clean(v).replace(/\D/g,'').replace(/^598/,'').replace(/^0/,'');
function video(raw){const v=clean(raw);if(!v)return '';const m=v.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([A-Za-z0-9_-]{6,})/i);return m?`https://www.youtube.com/embed/${m[1]}`:v}
function after(handler,mode){return(req,res,next)=>{const before=req.params?.id?store.findById(req.params.id):null,was=before?.status==='Publicada',ids=new Set(store.properties.map(p=>p.id));handler(req,res,next);let p=before;if(mode==='create')p=store.properties.find(x=>!ids.has(x.id));if(!p)return;const v=video(req.body?.videoUrl);if(mode.startsWith('user')&&was&&p.pendingChanges)p.pendingChanges.videoUrl=v;else p.videoUrl=v}}
exports.userCreate=after(base.userCreateProperty,'create');exports.userUpdate=after(base.userUpdateProperty,'user-update');exports.userPublishedChanges=after(base.userSubmitPublishedChanges,'user-published');exports.adminCreate=after(base.adminCreate,'create');exports.adminUpdate=after(base.adminUpdate,'admin');
exports.adminDashboard=(req,res,next)=>{const render=res.render.bind(res);res.render=(view,l={},cb)=>{if(view==='qcasa/admin/dashboard.njk'){l.stats=l.stats||{};l.stats.total=store.properties.length;l.stats.rejected=store.properties.filter(p=>p.status==='Rechazada').length;l.stats.drafts=store.properties.filter(p=>p.status==='Borrador').length;const pub=store.properties.filter(p=>p.status==='Publicada');l.opportunities={noVideo:pub.filter(p=>!p.videoUrl).length,lowPhotos:pub.filter(p=>!p.images||p.images.length<5).length,noInquiries:pub.filter(p=>!store.inquiries.some(i=>i.propertyId===p.id)).length,highInterest:pub.slice().sort((a,b)=>(b.views||0)-(a.views||0)).slice(0,3)}}return render(view,l,cb)};return base.adminDashboard(req,res,next)};
function qualityFor(p){const c=[['Fotos',p.images&&p.images.length>=5],['Ubicación',p.city&&p.department&&p.lat&&p.lng],['Descripción',clean(p.summary).length>=80],['Video',p.videoUrl],['Características',p.area&&(p.bedrooms||p.bathrooms||p.category)],['Contacto',p.ownerPhone||p.contact]];return{score:Math.round(c.filter(x=>x[1]).length/c.length*100),missing:c.filter(x=>!x[1]).map(x=>x[0]).join(' · ')}}
exports.detail=(req,res,next)=>{const render=res.render.bind(res);res.render=(view,l={},cb)=>{if(view==='qcasa/detail.njk'&&l.property){const p=l.property;l.galleryImages=JSON.stringify(p.images?.length?p.images:[p.image]).replace(/</g,'\\u003c');l.similar=store.properties.filter(x=>x.status==='Publicada'&&x.id!==p.id).slice(0,3)}return render(view,l,cb)};return base.detail(req,res,next)};
exports.adminProperties=(req,res)=>{const selected=clean(req.query.status)||'Todos',all=store.properties.slice().sort((a,b)=>new Date(b.updatedAt||b.createdAt||0)-new Date(a.updatedAt||a.createdAt||0)),counts={Todos:all.length,Publicada:all.filter(p=>p.status==='Publicada').length,Pendiente:all.filter(p=>p.status==='Pendiente').length,Rechazada:all.filter(p=>p.status==='Rechazada').length,Borrador:all.filter(p=>p.status==='Borrador').length,Cambios:all.filter(p=>p.changeStatus==='Pendiente'&&p.pendingChanges).length,Videos:all.filter(p=>p.videoUrl||p.pendingChanges?.videoUrl).length};let ps=all;if(selected==='Cambios')ps=all.filter(p=>p.changeStatus==='Pendiente'&&p.pendingChanges);else if(selected==='Videos')ps=all.filter(p=>p.videoUrl||p.pendingChanges?.videoUrl);else if(selected!=='Todos')ps=all.filter(p=>p.status===selected);res.render('qcasa/admin/properties.njk',{title:'Propiedades | Administración QCASA',properties:ps.map(p=>({...p,quality:qualityFor(p)})),selected,counts})};
exports.adminSetStatus=(req,res)=>{const p=store.findById(req.params.id);if(!p)return res.status(404).send('Propiedad no encontrada.');const s=clean(req.body.status);if(!['Borrador','Pendiente','Publicada','Rechazada'].includes(s))return res.status(400).send('Estado inválido.');const old=p.status;p.status=s;p.updatedAt=new Date().toISOString();if(s==='Publicada'){p.reviewedAt=new Date().toISOString();p.reviewNote='Publicada por administración.'}if(p.ownerUserId&&old!==s)store.addNotification(p.ownerUserId,{type:s==='Publicada'?'success':'info',title:`Estado actualizado: ${s}`,message:`"${p.title}" ahora está ${s.toLowerCase()}.`,propertyId:p.id});res.redirect(req.get('referer')||'/qcasa/admin/propiedades')};
function userFor(i){if(i.userId){const u=store.findUserById(i.userId);if(u)return u}return store.users.find(u=>(i.email&&email(i.email)===email(u.email))||(i.phone&&phone(i.phone)===phone(u.phone)))||null}
function belongs(i,u){return i.userId?i.userId===u.id:(i.email&&email(i.email)===email(u.email))||(i.phone&&phone(i.phone)===phone(u.phone))}
exports.inquiry=(req,res,next)=>{const ids=new Set(store.inquiries.map(i=>i.id)),u=req.session?.qcasaUser;base.inquiry(req,res,next);const i=store.inquiries.find(x=>!ids.has(x.id));if(i&&u)i.userId=u.id};
exports.contact=(req,res)=>{const reason=clean(req.body.reason)||'Consulta general',name=clean(req.body.name),ph=clean(req.body.phone),em=clean(req.body.email),message=clean(req.body.message);if(!name||!ph||!message)return res.status(400).send('Completá nombre, teléfono y mensaje.');store.inquiries.unshift({id:`CON-${Date.now()}`,propertyId:null,propertyTitle:`Contacto QCASA · ${reason}`,name,phone:ph,email:em,message,status:'Nueva',source:'Contacto general',reason,userId:req.session?.qcasaUser?.id||null,replies:[],createdAt:new Date().toISOString()});res.redirect('/qcasa?contacto=1')};
exports.userDashboard=(req,res,next)=>{const render=res.render.bind(res);res.render=(view,l={},cb)=>{if(view==='qcasa/user/dashboard.njk'&&l.user)l.myInquiries=store.inquiries.filter(i=>belongs(i,l.user)).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(i=>({...i,replies:Array.isArray(i.replies)?i.replies:[]}));return render(view,l,cb)};return base.userDashboard(req,res,next)};
exports.adminReplyInquiry=(req,res)=>{const i=store.findInquiry(req.params.id);if(!i)return res.status(404).send('Consulta no encontrada.');const message=clean(req.body.message);if(!message)return res.status(400).send('Escribí una respuesta.');if(!Array.isArray(i.replies))i.replies=[];i.replies.push({id:`R-${Date.now()}`,message,createdAt:new Date().toISOString(),author:'QCASA'});i.repliedAt=new Date().toISOString();i.lastReply=message;if(i.status==='Nueva')i.status='Contactado';const u=userFor(i);if(u){i.userId=u.id;store.addNotification(u.id,{type:'info',title:'QCASA respondió tu consulta',message:`Tenés una nueva respuesta sobre "${i.propertyTitle}".`,propertyId:i.propertyId||null})}res.redirect((req.get('referer')||'/qcasa/admin/consultas')+'#'+i.id)};
const demo=store.findById('QC-1001');if(demo&&!demo.videoUrl){demo.videoUrl='https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4';demo.videoLabel='Video demo'}